# Docker commands
up:
	docker compose up --build -d

up-no-build:
	docker compose up

down:
	docker compose down

shell:
	docker exec -it my_symfony_app /bin/sh

# Next commands
next_shell:
	docker exec -it nextjs_frontend sh

# Npm commands
npm_install:
	docker exec -it nextjs_frontend npm install
